# config/config.yaml
sites:
  - "https://мвд.рф/"
  - "https://госавтоинспекция.рф/"

monitoring_interval: 300  # Интервал мониторинга в секундах

notifications:
  telegram:
    enabled: false
    token: "YOUR_TELEGRAM_BOT_TOKEN"
    chat_id: "YOUR_CHAT_ID"
  email:
    enabled: false
    smtp_server: "smtp.example.com"
    smtp_port: 587
    username: "user@example.com"
    password: "password"
